# Start Player Seeds
players = Player.create([{
	# Start West Auckland Admirals
	# Start West Auckland Admirals Forwards
  "name": "Jake Ratcliffe",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 8,
  "gp": 15,
  "goals": 12,
  "assists": 6,
  "points": 18,
  "pim": 12,
  "plusMinus": 7,
	"abr": "WAA"
}, {
  "name": "Andy Hart",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 13,
  "gp": 15,
  "goals": 4,
  "assists": 20,
  "points": 24,
  "pim": 16,
  "plusMinus": 11,
	"abr": "WAA"
}, {
  "name": "Tom Tracy",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 77,
  "gp": 5,
  "goals": 3,
  "assists": 6,
  "points": 9,
  "pim": 2,
  "plusMinus": 3,
	"abr": "WAA"
}, {
  "name": "Zac Vince",
  "team": "West Auckland Admirals",
  "shoots": "Left",
  "position": "Forward",
	"posAbr": "F",
  "number": 40,
  "gp": 3,
  "goals": 0,
  "assists": 0,
  "points": 0,
  "pim": 0,
  "plusMinus": 1,
	"abr": "WAA"
}, {
  "name": "Ollie Curtis",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 6,
  "gp": 12,
  "goals": 0,
  "assists": 0,
  "points": 0,
  "pim": 0,
  "plusMinus": -2,
	"abr": "WAA"
}, {
  "name": "Max Vesper",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 13,
  "gp": 15,
  "goals": 4,
  "assists": 20,
  "points": 24,
  "pim": 16,
  "plusMinus": 11,
	"abr": "WAA"
}, {
  "name": "Steve Huish",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 7,
  "gp": 15,
  "goals": 2,
  "assists": 5,
  "points": 7,
  "pim": 4,
  "plusMinus": -1,
	"abr": "WAA"
}, {
  "name": "Dylan Dickson",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 16,
  "gp": 15,
  "goals": 4,
  "assists": 6,
  "points": 10,
  "pim": 2,
  "plusMinus": -2,
	"abr": "WAA"
}, {
  "name": "Taylor Rooney",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 35,
  "gp": 15,
  "goals": 1,
  "assists": 5,
  "points": 6,
  "pim": 10,
  "plusMinus": -1,
	"abr": "WAA"
}, {
  "name": "Nick Henderson",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 27,
  "gp": 14,
  "goals": 9,
  "assists": 13,
  "points": 22,
  "pim": 16,
  "plusMinus": 9,
	"abr": "WAA"
}, {
  "name": "Sam Pillidge",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 18,
  "gp": 8,
  "goals": 1,
  "assists": 1,
  "points": 2,
  "pim": 0,
  "plusMinus": 0,
	"abr": "WAA"
}, {
  "name": "Josh Rawiri",
  "team": "West Auckland Admirals",
  "shoots": "Left",
  "position": "Forward",
	"posAbr": "F",
  "number": 25,
  "gp": 6,
  "goals": 0,
  "assists": 0,
  "points": 0,
  "pim": 0,
  "plusMinus": -8,
	"abr": "WAA"
}, {
  "name": "Mark Rawiri",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Forward",
	"posAbr": "F",
  "number": 28,
  "gp": 11,
  "goals": 0,
  "assists": 0,
  "points": 0,
  "pim": 0,
  "plusMinus": -1,
	"abr": "WAA"
},
# Start West Auckland Admirals Defence
{
  "name": "Justin Daigle",
  "team": "West Auckland Admirals",
  "shoots": "Left",
  "position": "Defence",
	"posAbr": "D",
  "number": 47,
  "gp": 16,
  "goals": 1,
  "assists": 2,
  "points": 3,
  "pim": 30,
  "plusMinus": 0,
	"abr": "WAA"
}, {
  "name": "Blake Jackson",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Defence",
	"posAbr": "D",
  "number": 5,
  "gp": 15,
  "goals": 4,
  "assists": 8,
  "points": 12,
  "pim": 18,
  "plusMinus": 9,
	"abr": "WAA"
}, {
  "name": "Gareth McLeish",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Defence",
	"posAbr": "D",
  "number": 14,
  "gp": 15,
  "goals": 0,
  "assists": 6,
  "points": 6,
  "pim": 4,
  "plusMinus": -9,
	"abr": "WAA"
}, {
  "name": "Eric Chung",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Defence",
	"posAbr": "D",
  "number": 10,
  "gp": 6,
  "goals": 0,
  "assists": 1,
  "points": 1,
  "pim": 0,
  "plusMinus": 1,
	"abr": "WAA"
}, {
  "name": "Nick Craig",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Defence",
	"posAbr": "D",
  "number": 3,
  "gp": 15,
  "goals": 1,
  "assists": 8,
  "points": 9,
  "pim": 8,
  "plusMinus": -1,
	"abr": "WAA"
}, {
  "name": "Jono Pol",
  "team": "West Auckland Admirals",
  "shoots": "Right",
  "position": "Defence",
	"posAbr": "D",
  "number": 34,
  "gp": 7,
  "goals": 0,
  "assists": 0,
  "points": 0,
  "pim": 8,
  "plusMinus": -9,
	"abr": "WAA"
}, {
  "name": "Mat Roxborough",
  "team": "West Auckland Admirals",
  "shoots": "Left",
  "position": "Defence",
	"posAbr": "D",
  "number": 22,
  "gp": 10,
  "goals": 0,
  "assists": 0,
  "points": 0,
  "pim": 18,
  "plusMinus": -4,
	"abr": "WAA"
},
# Start West Auckland Admirals Goaltenders
{
	"name": "Rick Parry",
	"team": "West Auckland Admirals",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 54,
	"gp": 9,
	"gaa": 4.23,
	"svs": 882,
	"abr": "WAA"
}, {
	"name": "Csaba Kersco-Margos",
	"team": "West Auckland Admirals",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 34,
	"gp": 9,
	"gaa": 3.96,
	"svs": 893,
	"abr": "WAA"
},
# Start Canterbury Red Devils

# Start Canterbury Red Devils Forwards
{
	"name": "Chris Eaden",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 43,
	"gp": 16,
	"goals": 14,
	"assists": 14,
	"points": 28,
	"pim": 10,
	"plusMinus": 9,
	"abr": "CRD"
}, {
	"name": "Brad Apps",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 21,
	"gp": 16,
	"goals": 4,
	"assists": 4,
	"points": 8,
	"pim": 8,
	"plusMinus": -9,
	"abr": "CRD"
}, {
	"name": "Alex Ashwell",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Shaun Brown",
	"team": "Canterbury Red Devils",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 19,
	"gp": 16,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -3,
	"abr": "CRD"
}, {
	"name": "Liam Dallimore",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 14,
	"gp": 12,
	"goals": 4,
	"assists": 1,
	"points": 5,
	"pim": 4,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Alex Damm",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 0,
	"gp": 6,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Alex Egan",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 88,
	"gp": 7,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "CRD"
}, {
	"name": "Justin Fuller",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 17,
	"gp": 14,
	"goals": 6,
	"assists": 7,
	"points": 13,
	"pim": 4,
	"plusMinus": 2,
	"abr": "CRD"
}, {
	"name": "Jeong Kim",
	"team": "Canterbury Red Devils",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Luke Hill",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 18,
	"gp": 7,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Jaxson Lane",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 10,
	"gp": 16,
	"goals": 3,
	"assists": 5,
	"points": 8,
	"pim": 14,
	"plusMinus": -4,
	"abr": "CRD"
}, {
	"name": "Anton Purver",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 61,
	"gp": 16,
	"goals": 1,
	"assists": 1,
	"points": 2,
	"pim": 4,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Nik Stefanissin",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
},
# Start Canterbury Red Devils Defence
{
	"name": "Moses Bygate-Smith",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 12,
	"gp": 10,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "CRD"
}, {
	"name": "Ryan Fraser",
	"team": "Canterbury Red Devils",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Mason Kennedy",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 8,
	"gp": 15,
	"goals": 0,
	"assists": 4,
	"points": 4,
	"pim": 14,
	"plusMinus": 1,
	"abr": "CRD"
}, {
	"name": "Henry Morley-Hall",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 0,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
}, {
	"name": "Kyle Nash",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 79,
	"gp": 11,
	"goals": 0,
	"assists": 1,
	"points": 1,
	"pim": 4,
	"plusMinus": -1,
	"abr": "CRD"
}, {
	"name": "Mason Rees",
	"team": "Canterbury Red Devils",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 27,
	"gp": 4,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "CRD"
},
# Start Canterbury Red Devils Goaltenders
{
	"name": "Michael Coleman",
	"team": "Canterbury Red Devils",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 1,
	"gp": 9,
	"gaa": 4.49,
	"svs": 899,
	"abr": "CRD"
}, {
	"name": "Steven Coull",
	"team": "Canterbury Red Devils",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 35,
	"gp": 2,
	"gaa": 13.02,
	"svs": 784,
	"abr": "CRD"
}, {
	"name": "Richard Bigsby",
	"team": "Canterbury Red Devils",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 0,
	"gp": 0,
	"gaa": 0.00,
	"svs": 000,
	"abr": "CRD"
},
# Start Skycity Stampede

# Start Skycity Stampede Forwards
{
	"name": "Matt Schneider",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 4,
	"gp": 10,
	"goals": 14,
	"assists": 9,
	"points": 23,
	"pim": 2,
	"plusMinus": 12,
	"abr": "STP"
}, {
	"name": "Luke Pickering",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 6,
	"gp": 16,
	"goals": 2,
	"assists": 2,
	"points": 4,
	"pim": 10,
	"plusMinus": 5,
	"abr": "STP"
}, {
	"name": "Cameron White",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 7,
	"gp": 13,
	"goals": 1,
	"assists": 0,
	"points": 1,
	"pim": 4,
	"plusMinus": -3,
	"abr": "STP"
}, {
	"name": "Braden Lee",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 12,
	"gp": 16,
	"goals": 7,
	"assists": 5,
	"points": 12,
	"pim": 8,
	"plusMinus": 10,
	"abr": "STP"
}, {
	"name": "Mike McRae",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 13,
	"gp": 16,
	"goals": 12,
	"assists": 25,
	"points": 37,
	"pim": 24,
	"plusMinus": 28,
	"abr": "STP"
}, {
	"name": "Callum Burns",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 14,
	"gp": 16,
	"goals": 6,
	"assists": 5,
	"points": 11,
	"pim": 12,
	"plusMinus": 11,
	"abr": "STP"
}, {
	"name": "Harrison Macharg",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 17,
	"gp": 8,
	"goals": 3,
	"assists": 3,
	"points": 6,
	"pim": 27,
	"plusMinus": 9,
	"abr": "STP"
}, {
	"name": "Stefan King",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 19,
	"gp": 2,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "STP"
}, {
	"name": "Taylor Stewart",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 21,
	"gp": 7,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "STP"
}, {
	"name": "Max Macharg",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 25,
	"gp": 6,
	"goals": 2,
	"assists": 1,
	"points": 3,
	"pim": 37,
	"plusMinus": 5,
	"abr": "STP"
}, {
	"name": "Bryn Murray",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 27,
	"gp": 11,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "STP"
}, {
	"name": "Ryan Strayer",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 56,
	"gp": 5,
	"goals": 0,
	"assists": 3,
	"points": 3,
	"pim": 0,
	"plusMinus": 3,
	"abr": "STP"
},
# Start Skycity Stampede Defence
{
	"name": "Bert Haines",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 2,
	"gp": 16,
	"goals": 1,
	"assists": 2,
	"points": 3,
	"pim": 30,
	"plusMinus": 0,
	"abr": "STP"
}, {
	"name": "Stefan Helmersson",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 3,
	"gp": 16,
	"goals": 3,
	"assists": 8,
	"points": 11,
	"pim": 12,
	"plusMinus": 13,
	"abr": "STP"
}, {
	"name": "Cameron Trew",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 8,
	"gp": 16,
	"goals": 1,
	"assists": 1,
	"points": 2,
	"pim": 22,
	"plusMinus": 17,
	"abr": "STP"
}, {
	"name": "Cameron Frear",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 9,
	"gp": 16,
	"goals": 0,
	"assists": 1,
	"points": 1,
	"pim": 12,
	"plusMinus": 6,
	"abr": "STP"
}, {
	"name": "Ben Harford",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 11,
	"gp": 16,
	"goals": 0,
	"assists": 3,
	"points": 3,
	"pim": 6,
	"plusMinus": -1,
	"abr": "STP"
}, {
	"name": "Mitchell Frear",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 16,
	"gp": 16,
	"goals": 1,
	"assists": 12,
	"points": 13,
	"pim": 4,
	"plusMinus": 14,
	"abr": "STP"
}, {
	"name": "Hayden Argyle",
	"team": "Skycity Stampede",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 22,
	"gp": 14,
	"goals": 2,
	"assists": 5,
	"points": 7,
	"pim": 49,
	"plusMinus": 9,
	"abr": "STP"
}, {
	"name": "Ben Miller",
	"team": "Skycity Stampede",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 31,
	"gp": 8,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "STP"
},
# Start Skycity Stampede Goaltenders
{
	"name": "Aston Brookes",
	"team": "Skycity Stampede",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 39,
	"gp": 7,
	"gaa": 1.55,
	"svs": 944,
	"abr": "STP"
}, {
	"name": "Matt Swirtz",
	"team": "Skycity Stampede",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 1,
	"gp": 1,
	"gaa": 6.00,
	"svs": 854,
	"abr": "STP"
},
# Start Botany Swarm

# Start Swarm Forwards
{
	"name": "Michael Attwell",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 6,
	"gp": 15,
	"goals": 5,
	"assists": 8,
	"points": 13,
	"pim": 30,
	"plusMinus": -7,
	"abr": "BSW"
}, {
	"name": "Aaron Henderson",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 7,
	"gp": 6,
	"goals": 0,
	"assists": 2,
	"points": 2,
	"pim": 0,
	"plusMinus": 1,
	"abr": "BSW"
}, {
	"name": "Robyn Vortanov",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 8,
	"gp": 16,
	"goals": 1,
	"assists": 2,
	"points": 3,
	"pim": 8,
	"plusMinus": -1,
	"abr": "BSW"
}, {
	"name": "Alexander Polozov",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 10,
	"gp": 15,
	"goals": 4,
	"assists": 11,
	"points": 15,
	"pim": 37,
	"plusMinus": -2,
	"abr": "BSW"
}, {
	"name": "Ritchie Hopkinson",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 11,
	"gp": 12,
	"goals": 3,
	"assists": 5,
	"points": 8,
	"pim": 0,
	"plusMinus": 0,
	"abr": "BSW"
}, {
	"name": "Matthew Taylor",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 12,
	"gp": 14,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -8,
	"abr": "BSW"
}, {
	"name": "Thomas Clow",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 16,
	"gp": 3,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "BSW"
}, {
	"name": "Dion Guest",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 17,
	"gp": 5,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 4,
	"plusMinus": 0,
	"abr": "BSW"
}, {
	"name": "Kyle Jonsson",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 18,
	"gp": 14,
	"goals": 1,
	"assists": 1,
	"points": 2,
	"pim": 0,
	"plusMinus": -1,
	"abr": "BSW"
}, {
	"name": "Aaron Henderson",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 7,
	"gp": 6,
	"goals": 0,
	"assists": 2,
	"points": 2,
	"pim": 0,
	"plusMinus": 1,
	"abr": "BSW"
}, {
	"name": "K.C Ball",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 14,
	"gp": 16,
	"goals": 0,
	"assists": 9,
	"points": 9,
	"pim": 6,
	"plusMinus": -8,
	"abr": "BSW"
}, {
	"name": "Oliver Hay",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 21,
	"gp": 15,
	"goals": 2,
	"assists": 6,
	"points": 8,
	"pim": 47,
	"plusMinus": -7,
	"abr": "BSW"
}, {
	"name": "Sami Saastamoinen",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 25,
	"gp": 15,
	"goals": 12,
	"assists": 11,
	"points": 23,
	"pim": 34,
	"plusMinus": 7,
	"abr": "BSW"
}, {
	"name": "Maxim Kaluzhny",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 27,
	"gp": 9,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -2,
	"abr": "BSW"
},
# Start Swarn Defence
{
	"name": "Jamie Lawrence",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 2,
	"gp": 16,
	"goals": 5,
	"assists": 6,
	"points": 11,
	"pim": 35,
	"plusMinus": -6,
	"abr": "BSW"
}, {
	"name": "Kahu Joyce",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 5,
	"gp": 13,
	"goals": 1,
	"assists":1,
	"points": 2,
	"pim": 6,
	"plusMinus": -8,
	"abr": "BSW"
}, {
	"name": "Andrew Hay",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 13,
	"gp": 16,
	"goals": 0,
	"assists": 3,
	"points": 3,
	"pim": 10,
	"plusMinus": -4,
	"abr": "BSW"
}, {
	"name": "Stephen Mawson",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 14,
	"gp": 16,
	"goals": 2,
	"assists": 0,
	"points": 2,
	"pim": 4,
	"plusMinus": -6,
	"abr": "BSW"
}, {
	"name": "Steven Adams",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 20,
	"gp": 10,
	"goals": 0,
	"assists": 4,
	"points": 4,
	"pim": 6,
	"plusMinus": 2,
	"abr": "BSW"
}, {
	"name": "Leith Thompson",
	"team": "Botany Swarm",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 23,
	"gp": 10,
	"goals": 1,
	"assists": 1,
	"points": 2,
	"pim": 2,
	"plusMinus": -1,
	"abr": "BSW"
}, {
	"name": "Logan Fraser",
	"team": "Botany Swarm",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 24,
	"gp": 13,
	"goals": 2,
	"assists": 3,
	"points": 5,
	"pim": 4,
	"plusMinus": 3,
	"abr": "BSW"
},
# Start Botany Swarm Goaltenders
{
	"name": "Michael Hopkinson",
	"team": "Botany Swarm",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 1,
	"gp": 10,
	"gaa": 4.29,
	"svs": 854,
	"abr": "BSW"
}, {
	"name": "Alain Giauque",
	"team": "Botany Swarm",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 30,
	"gp": 8,
	"gaa": 3.97,
	"svs": 895,
	"abr": "BSW"
}, {
	"name": "Grace Harrison",
	"team": "Botany Swarm",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 32,
	"gp": 2,
	"gaa": 12.55,
	"svs": 714,
	"abr": "BSW"
},
# Start Dunedin Thunder

# Start Dunedin Thunder Forwards
{
	"name": "Gareth Lloyd",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 40,
	"gp": 5,
	"goals": 3,
	"assists": 0,
	"points": 3,
	"pim": 2,
	"plusMinus": -6,
	"abr": "THU"
}, {
	"name": "Jaan Turia",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 13,
	"gp": 5,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "THU"
}, {
	"name": "Thomas Carson-Pratt",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 12,
	"gp": 15,
	"goals": 1,
	"assists": 4,
	"points": 5,
	"pim": 24,
	"plusMinus": -11,
	"abr": "THU"
}, {
	"name": "Shaun Harrison",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 22,
	"gp": 15,
	"goals": 3,
	"assists": 4,
	"points": 7,
	"pim": 14,
	"plusMinus": -11,
	"abr": "THU"
}, {
	"name": "Jacob Hurring",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 61,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "THU"
}, {
	"name": "Joel Scott",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 36,
	"gp": 13,
	"goals": 0,
	"assists": 1,
	"points": 1,
	"pim": 2,
	"plusMinus": -4,
	"abr": "THU"
}, {
	"name": "Joe Orr",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Forward",
	"posAbr": "F",
	"number": 90,
	"gp": 13,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 8,
	"plusMinus": -9,
	"abr": "THU"
}, {
	"name": "Ben Roth",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 81,
	"gp": 9,
	"goals": 0,
	"assists": 1,
	"points": 1,
	"pim": 4,
	"plusMinus": -1,
	"abr": "THU"
}, {
	"name": "Noah Leahy",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Forward",
	"posAbr": "F",
	"number": 35,
	"gp": 8,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 2,
	"plusMinus": -2,
	"abr": "THU"
},
#  Start Dunedin Thunder Defence
{
	"name": "Regan Wilson",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 19,
	"gp": 10,
	"goals": 0,
	"assists": 2,
	"points": 2,
	"pim": 6,
	"plusMinus": -9,
	"abr": "THU"
}, {
	"name": "Filipe Aquirre",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 5,
	"gp": 0,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": 0,
	"abr": "THU"
}, {
	"name": "George Hopkins",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 11,
	"gp": 9,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 0,
	"plusMinus": -1,
	"abr": "THU"
}, {
	"name": "Dylan Devlin",
	"team": "Dunedin Thunder",
	"shoots": "Right",
	"position": "Defence",
	"posAbr": "D",
	"number": 12,
	"gp": 8,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 2,
	"plusMinus": -4,
	"abr": "THU"
}, {
	"name": "Matas Barakauskas",
	"team": "Dunedin Thunder",
	"shoots": "Left",
	"position": "Defence",
	"posAbr": "D",
	"number": 6,
	"gp": 12,
	"goals": 0,
	"assists": 0,
	"points": 0,
	"pim": 2,
	"plusMinus": -5,
	"abr": "THU"
},
# Start Thunder Goaltenders
{
	"name": "Hunter Waugh",
	"team": "Dunedin Thunder",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 29,
	"gp": 0,
	"gaa": 0.00,
	"svs": 0,
	"abr": "DNT"
}, {
	"name": "Jonas Barakauskas",
	"team": "Dunedin Thunder",
	"catches": "Left",
	"position": "Goalie",
	"posAbr": "GK",
	"number": 88,
	"gp": 6,
	"gaa": 6.53,
	"svs": 872,
	"abr": "DNT"
}])

p "Added #{Player.count} players"
